Colu-948 burn
Colu-platform/coloredcoinsd-wraper pull request #1
Opened 2016-11-07 19:44 UTC by oleiba

2016-11-08 13:35 UTC, tal-beja commented on test/test.js
>        assert(err)
This is not returning an error any more? because this is a transaction that already on the block-chain

2016-11-08 13:37 UTC, tal-beja requested changes
`broadcastTx` is not returning an error any more? because this is a transaction that already on the block-chain

2016-11-09 08:58 UTC, oleiba commented on test/test.js
>        assert(err)
It does return an error, but not the specified expected error.
I will open a separate issue so such an error will be returned again (it does not relate to my changes).

2016-11-09 08:58 UTC, tal-beja approved these changes

2016-11-09 09:22 UTC, merged